### ISSUE TITLE
[Enhancement] Implementing a url for liveness and readyness probe

### ISSUE THREAD

**Issue by sjedlick** [telekom-mms/trivy-dojo-report-operator#22]
### Description

It would be nice if trivy-dojo-report-operator could provide a http get path (like /healthz)  which could be used for liveness and readyness probe.

For example:
```
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
```
